language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"


script:
  - npm run test:ci

after_success:
  - ./node_modules/.bin/bithound check git@github.com:thibmaek/bpost.git
  - bash <(curl -s https://codecov.io/bash)
